## You should change each of the following fields
## to customize your blog

title: Data Dives
description: This blog is designed to provide introductory, yet in-depth insights into different areas of data science. You will be able to find articles, graphics, and posts written and posted by me, Talmage Hilton. If you have any questions, concerns, or critiques, please reach out to me on my socials! Enjoy!
author: Talmage Hilton
author_description: I am a current BYU undergraduate student majoring in statistics! I am from South Jordan, Utah and I love sports, music, and data science.

url: https://Talmage-Hilton.github.io ## change this to https://yourusername.github.io
baseurl: Stat-386-Blog ## change this to the name of your blog repository
header_image: /assets/img/data_science_face.jpg ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github:  Talmage-Hilton
    twitter: 
    facebook: talmage.hilton
    email: 
    linkedin: talmage-hilton
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




